# Generated by Django 3.1.7 on 2021-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('fb_profile', models.CharField(max_length=255)),
                ('twitter_profile', models.CharField(max_length=255)),
                ('linkedin_profile', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
    ]
