# Generated by Django 3.1.7 on 2021-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210226_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('color', models.CharField(default='424244', max_length=6)),
                ('tasks', models.ManyToManyField(blank=True, to='tasks.Task')),
            ],
        ),
    ]
